### ISSUE TITLE
Broken install on Windows 10

### ISSUE THREAD

**Issue by LaFa777** [orsinium/rutimeparser#1]
Error during installation from pip.

Windows 10
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

```
Collecting rutimeparser
  Downloading https://files.pythonhosted.org/packages/15/89/ca52b53bca0a486d3a0ad33e00d8a64ea9270817cbe57fd55b2ac9211fc0/rutimeparser-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kirill\AppData\Local\Temp\pip-install-3hw9gqxn\rutimeparser\setup.py", line 12, in <module>
        long_description=open('README.rst').read(),
      File "C:\Users\kirill\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 331: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\kirill\AppData\Local\Temp\pip-install-3hw9gqxn\rutimeparser\
```

**Comment by LaFa777** [comment]
#2
